In [2]:
from sklearn.datasets import load_digits 

In [3]:
digits = load_digits()

In [5]:
digits.data,digits.target

(array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 array([0, 1, 2, ..., 8, 9, 8]))

In [6]:
import tensorflow as tf 

In [8]:
from tensorflow.keras.models import Sequential

In [10]:
from tensorflow.keras.layers import Dense

In [11]:
classifier = Sequential()

In [12]:
X = digits.data
Y = digits.target
len(X[0])

64

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.25)

In [21]:
classifier.add(Dense(units=16,activation='relu',kernel_initializer='he_uniform',input_dim = X_train.shape[1]))
classifier.add(Dense(units=16,activation='relu',kernel_initializer='he_uniform'))
classifier.add(Dense(units=10,activation='softmax',kernel_initializer='he_uniform'))

In [56]:
classifier.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [37]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import pandas as pd

In [72]:
Y_train.reshape(-1,1)

array([[3],
       [9],
       [0],
       ...,
       [0],
       [4],
       [5]])

In [74]:
encoder = OneHotEncoder(categories = 'auto')
X = encoder.fit_transform(Y_train.reshape(-1,1)).toarray()
print(X)
dfonehot = pd.DataFrame(X)
dfonehot

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


0    1    2    3    4    5    6    7    8    9
0     0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
2     1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
4     0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
1342  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
1343  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1344  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1345  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
1346  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0

[1347 rows x 10 columns]

In [76]:
classifier.fit(x=X_train,y=dfonehot,validation_split=0.33,batch_size = 10,epochs = 50)

Epoch 1/50
91/91 [==============================] - 1s 7ms/step - loss: 0.1549 - accuracy: 0.8991 - val_loss: 0.5669 - val_accuracy: 0.8360
Epoch 2/50
91/91 [==============================] - 1s 8ms/step - loss: 0.1476 - accuracy: 0.8947 - val_loss: 0.5566 - val_accuracy: 0.8135
Epoch 3/50
91/91 [==============================] - 1s 6ms/step - loss: 0.1406 - accuracy: 0.9169 - val_loss: 0.5876 - val_accuracy: 0.8360
Epoch 4/50
91/91 [==============================] - 1s 10ms/step - loss: 0.1401 - accuracy: 0.9157 - val_loss: 0.5470 - val_accuracy: 0.8382
Epoch 5/50
91/91 [==============================] - 1s 7ms/step - loss: 0.1380 - accuracy: 0.9113 - val_loss: 0.5904 - val_accuracy: 0.8225
Epoch 6/50
91/91 [==============================] - 1s 6ms/step - loss: 0.1374 - accuracy: 0.9202 - val_loss: 0.5820 - val_accuracy: 0.8382
Epoch 7/50
91/91 [==============================] - 1s 6ms/step - loss: 0.1380 - accuracy: 0.9146 - val_loss: 0.6951 - val_accuracy: 0.8135
Epoch 8/50
91/91 [=

In [59]:
pred = classifier.predict(X_test)

15/15 [==============================] - 0s 3ms/step


In [60]:
from sklearn.metrics import accuracy_score

In [65]:
for i in pred[0]:
    print(i*100) 

1.0166726488458622e-08
7.410462000978502e-10
99.9496340751648
0.010158878285437822
0.0
1.0187786181890032e-12
5.975505645849921e-08
4.228136345173251e-27
0.03622558724600822
0.003973079583374783


In [66]:
Y_test[0]

2